#!/bin/sh

lteproto=$(cat /etc/config/network | grep -c "proto 'modemmanager'")
if [ "$lteproto" -eq "0" ]; then
file1=$(mktemp)
ping -W 2 -c 1 9.9.9.9 > /dev/null 2>&1
picocom -t "$(printf 'AT+QCAINFO\r\n')" /dev/ttyUSB2 --nolock --exit-after 300 --quiet --logfile "$file1" > /dev/null
cat "$file1"
rm "$file1"
else
echo "Script not compatible with \"ModemManager\""
exit 1
fi
