#!/bin/sh
LTEPROTO=$(cat /etc/config/network | grep -E "proto 'qmi'|proto 'mbim'|proto 'dhcp'" | wc -l)
if [ ${LTEPROTO} -eq "1" ]; then
file1=$(mktemp)

ping -W 2 -c 1 9.9.9.9 > /dev/null 2>&1
picocom -t "$(echo -ne 'AT+QCAINFO\r\n')" /dev/ttyUSB2 --nolock --exit-after 300 --quiet --logfile $file1 >/dev/null
cat $file1

rm $file1
fi
