#!/bin/sh

# Turn off all led (exclude lan and wlan)
echo 0 > /sys/class/leds/green:power/brightness
echo 0 > /sys/class/leds/red:info/brightness
#echo 0 > /sys/class/leds/green:lan/brightness
#echo 0 > /sys/class/leds/green:wlan/brightness
echo 0 > /sys/class/leds/amber:info/brightness
echo 0 > /sys/class/leds/green:wan/brightness
