#!/bin/sh

deletesms(){
printf "\ndelete all SMS\n"
sms_tool -d /dev/ttyUSB2 delete all >/dev/null 2>&1
echo 0 > /sys/class/leds/green:voice/brightness
}

nodeletesms(){
printf "\nno delete SMS\n"
}

lteproto=$(cat /etc/config/network | grep -c "proto 'modemmanager'")
if [ "$lteproto" -eq "0" ]; then
    sms_tool -d /dev/ttyUSB2 -s SM status
    sms_tool -d /dev/ttyUSB2 -s ME status
    sms_tool -d /dev/ttyUSB2 -s SR status
    sms_tool -d /dev/ttyUSB2 -s MT status
    sms_tool -d /dev/ttyUSB2 recv

    printf "you want to delete all SMS [y,n]\n"
    read -r -n1 question
    case "$question" in
    y*|Y*) deletesms ;;
    n*|N*) nodeletesms ;;
    *) printf "invalid option\n"; exit 1;;
    esac
else
    printf "Script not compatible with \"ModemManager\"\n"
    exit 1
fi
