#!/bin/sh
MEM_AVAIL="$(ubus call system info | jsonfilter -e "@['memory']['available']")"
MEM_LIM="40000000"
logger "MEMORY MEM_AVAIL ${MEM_AVAIL}"
#if [ "${MEM_AVAIL}" -lt "${MEM_LIM}" ]; then
#reboot
#fi
