#!/bin/sh
# for 600 sec from boot not exec nothing
statuptime=$(cut -f1 -d. /proc/uptime)
if [ "$statuptime" -lt "600" ]; then
# if proto=qmi then it proceeds otherwise it does nothing
lteproto=$(cat /etc/config/network | grep -c "proto 'qmi'")
    if [ "$lteproto" -eq "1" ]; then
    ltestatus=$(uqmi -d /dev/cdc-wdm0 -t 20000 --get-data-status)
    lteerror=$?
    ltefind=$(echo ${ltestatus} | grep -c "\"connected\"")
        if [ "$lteerror" -ne "0" ]; then
        logger "exec: /root/wan_connect: uqmi not response into 20 sec exec ifdown wan; ifup wan"
        ifdown wan && ifup wan
        fi
        if [ "$ltefind" -eq "0" ]; then
        logger "exec: /root/wan_connect: lost connection detected exec ifdown wan; ifup wan"
        ifdown wan &&   ifup wan
        fi
    fi
fi
