#!/bin/sh
# for 600 sec from boot not exec nothing
statuptime=$(cut -f1 -d. /proc/uptime)
if [ "$statuptime" -lt "600" ]; then
# if proto=qmi then it proceeds otherwise it does nothing
lteproto=$(cat /etc/config/network | grep -c "proto 'qmi'")
    if [ "$lteproto" -eq "1" ]; then
    ltestatus=$(uqmi -d /dev/cdc-wdm0 -t 20000 --get-data-status)
    lteerror=$?
    ltefind=$(echo "$ltestatus" | grep -c "\"connected\"")
        if [ "$ltefind" -eq "0" ] || [ "$lteerror" -ne "0" ] ; then
        logger "exec: /root/wan_connect: lost connection detected or uqmi not response into 20 sec exec ifup wan"
        # ifdown not necessary from: https://forum.openwrt.org/t/what-is-the-command-to-restart-wan6/107810/2
        # ifdown wan && ifup wan
        ifup wan
        fi
    fi
fi
